### ISSUE TITLE
Rerouting audio output of some applications

### ISSUE THREAD

**Issue by lentrodev** [residuum/JackSharp#2]
I would like to reroute output of some applications to selected device. For example the output from game to headphones, output from browser to loudspeakers, etc. How I can realize that idea, and this possible with this library or not?

**Comment by residuum** [comment]
Yes and no. You have to have [Jack](http://jackaudio.org/) installed, and your applications must be able to use the Jack API. If you only want to route other applications, then [QjackCtl](https://qjackctl.sourceforge.io/) is one possibility. Windows (and probably Mac OS) downloads of Jack include it, Linux distributions usually have both applications as different packages.

This library can be used to develop your own client for Jack.

**Comment by lentrodev** [comment]
Thanks!
